namespace Maps {
    void generateStatStrings();
}

// enum for all stat indexes 
// easier to refer back to stat names
// total stats are from 0 to 30, game stats from 31 to end
enum stats {
    wins,
    losses,
    mvps,
    games,
    // end of stats without game counterpart
    STATSWITHOUTGAME = games,
    goals,
    demos,
    deaths,
    exterms,
    aerialGoals,
    backwardsGoals,
    bicycleGoals,
    longGoals,
    turtleGoals,
    poolShots,
    overtimeGoals,
    hatTricks,
    assists,
    playmakers,
    saves,
    epicSaves,
    saviors,
    shots,
    centers,
    clears,
    firstTouchs,
    damages,
    ultraDamages,
    lowFives,
    highFives,
    swishs,
    bicycleHits,
    points,
    totalSaves,
    ownGoals,
    KO_LightHit,
    KO_HeavyHit,
    KO_Knockout,
    KO_DoubleKO,
    KO_HitTaken,
    KO_Death,
    KO_LightBlock,
    KO_HeavyBlock,
    KO_BlockTaken,
    KO_Grabbed,
    KO_Thrown,
    KO_AerialLightHit,
    KO_PlayerGrabbed,
    KO_PlayerThrown,
    KO_AerialHeavyHit,
    KO_KnockoutAssist,
    KO_Winner,
    // last stat with normal output type
    ENDNORMALSTATS = KO_Winner + 1,
    timePlayed = ENDNORMALSTATS,
    offenseTime,
    defenseTime,
    // total number of stats in the stat array
    NUMSTATS
};

static std::string statStringsStandard[NUMSTATS] = {
    "wins",
    "losses",
    "mvps",
    "games",
    "goals",
    "demolitions",
    "deaths",
    "exterminations",
    "aerialGoals",
    "backwardsGoals",
    "bicycleGoals",
    "longGoals",
    "turtleGoals",
    "poolShots",
    "overtimeGoals",
    "hatTricks",
    "assists",
    "playmakers",
    "saves",
    "epicSaves",
    "saviors",
    "shots",
    "centers",
    "clears",
    "firstTouchs",
    "damages",
    "ultraDamages",
    "lowFives",
    "highFives",
    "swishs",
    "bicycleHits",
    "points",
    "totalSaves",
    "ownGoals",
    "KO_LightHit",
    "KO_HeavyHit",
    "KO_Knockout",
    "KO_DoubleKO",
    "KO_HitTaken",
    "KO_Death",
    "KO_LightBlock",
    "KO_HeavyBlock",
    "KO_BlockTaken",
    "KO_Grabbed",
    "KO_Thrown",
    "KO_AerialLightHit",
    "KO_PlayerGrabbed",
    "KO_PlayerThrown",
    "KO_AerialHeavyHit",
    "KO_KnockoutAssist",
    "KO_Winner",
    "timePlayed",
    "offenseTime",
    "defenseTime"
};

static const char* statCharStandard[NUMSTATS] = {
    "Wins",
    "Losses",
    "MVPs",
    "Games",
    "Goals",
    "Demolitions",
    "Deaths",
    "Exterminations",
    "Aerial Goals",
    "Backwards Goals",
    "Bicycle Goals",
    "Long Goals",
    "Turtle Goals",
    "Pool Shots",
    "Overtime Goals",
    "Hat Tricks",
    "Assists",
    "Playmakers",
    "Saves",
    "Epic Saves",
    "Saviors",
    "Shots",
    "Centers",
    "Clears",
    "First Touchs",
    "Damages",
    "Ultra Damages",
    "Low Fives",
    "High Fives",
    "Swishes",
    "Bicycle Hits",
    "Points",
    "Total Saves",
    "Own Goals",
    "KO Light Hits",
    "KO Heavy Hits",
    "KO Knockouts",
    "KO Double KOs",
    "KO Hits Taken",
    "KO Deaths",
    "KO Light Blocks",
    "KO Heavy Blocks",
    "KO Blocks Taken",
    "KO Times Grabbed",
    "KO Times Thrown",
    "KO Aerial Light Hits",
    "KO Players Grabbed",
    "KO Players Thrown",
    "KO Aerial Heavy Hit",
    "KO Knockout Assists",
    "KO Wins",
    "Time Played",
    "Offense Time",
    "Defense Time"
};

extern std::string renderStringsStandard[NUMSTATS];

extern std::string statStringsGame[NUMSTATS];
extern std::string renderStringsGame[NUMSTATS];

extern std::string statStringsAverage[NUMSTATS];
extern std::string renderStringsAverage[NUMSTATS];

static const std::map<std::string, int> eventDictionary = {
    { "Demolish", demos},
    { "Demolition", exterms},
    { "Goal", goals},
    { "Win", wins},
    { "MVP", mvps},
    { "AerialGoal", aerialGoals},
    { "BackwardsGoal", backwardsGoals},
    { "BicycleGoal", bicycleGoals},
    { "LongGoal", longGoals},
    { "TurtleGoal", turtleGoals},
    { "PoolShot", poolShots},
    { "OvertimeGoal", overtimeGoals},
    { "HatTrick", hatTricks},
    { "Assist", assists},
    { "Playmaker", playmakers},
    { "Save", saves},
    { "EpicSave", epicSaves},
    { "Savior", saviors},
    { "Shot", shots},
    { "Center", centers},
    { "Clear", clears},
    { "FirstTouch", firstTouchs},
    { "BreakoutDamage", damages},
    { "BreakoutDamageLarge", ultraDamages},
    { "LowFive", lowFives},
    { "HighFive", highFives},
    { "HoopsSwishGoal", swishs},
    { "BicycleHit", bicycleHits},
    { "OwnGoal", ownGoals},
    { "KO_LightHit", KO_LightHit},
    { "KO_HeavyHit", KO_HeavyHit},
    { "KO_Knockout", KO_Knockout},
    { "KO_DoubleKO", KO_DoubleKO},
    { "KO_HitTaken", KO_HitTaken},
    { "KO_Death", KO_Death},
    { "KO_LightBlock", KO_LightBlock},
    { "KO_HeavyBlock", KO_HeavyBlock},
    { "KO_BlockTaken", KO_BlockTaken},
    { "KO_Grabbed", KO_Grabbed},
    { "KO_Thrown", KO_Thrown},
    { "KO_AerialLightHit", KO_AerialLightHit},
    { "KO_PlayerGrabbed", KO_PlayerGrabbed},
    { "KO_PlayerThrown", KO_PlayerThrown},
    { "KO_AerialHeavyHit", KO_AerialHeavyHit},
    { "KO_KnockoutAssist", KO_KnockoutAssist},
    { "KO_Winner", KO_Winner},
};

enum otherStats {
    shootingPercentage,
    gameShootingPercentage,
    kDRatio,
    gameKDRatio,
    possibleExterminations,
    missedExterminationPercent,
    winPercentage,
    NUMOTHERSTATS
};

static std::string statStringsOther[NUMOTHERSTATS] = {
    "shootingPercentage",
    "gameShootingPercentage",
    "kDRatio",
    "gameKDRatio",
    "possibleExterminations",
    "missedExterminationPercent",
    "winPercentage"
};

static const char* statCharOther[NUMOTHERSTATS] = {
    "Shooting Percentage",
    "Game Shooting Percentage",
    "KD Ratio",
    "Game KD Ratio",
    "Possible Exterminations",
    "Missed Extermination Percent",
    "Win Percentage"
};

extern std::string renderStringsOther[NUMOTHERSTATS];

enum careerStats {
    FirstTouch,
    Shot,
    Goal,
    Center,
    HatTrick,
    Clear,
    Win,
    MVP,
    Assist,
    Demolish,
    Save,
    Loss,
    AerialHit,
    EpicSave,
    LongGoal,
    PoolShot,
    BicycleHit,
    BackwardsGoal,
    JuggleHit,
    Playmaker,
    OvertimeGoal,
    Savior,
    FewestBallTouches,
    CarTouches,
    FastestGoal,
    SlowestGoal,
    FurthestGoal,
    MostBallTouches,
    MostBoostPickups,
    Demolition,
    BicycleGoal,
    AerialGoal,
    FreezeSave,
    OwnGoal,
    TurtleGoal,
    FewestBoostPickups,
    BreakoutDamage,
    BreakoutDamageLarge,
    TimePlayed,
    LowFive,
    HoopsSwishGoal,
    BallHit,
    HighFive,
    BoostPickups,
    Game,
    KO_LightHit_C,
    KO_HeavyHit_C,
    KO_Knockout_C,
    KO_DoubleKO_C,
    KO_HitTaken_C,
    KO_Death_C,
    KO_LightBlock_C,
    KO_HeavyBlock_C,
    KO_BlockTaken_C,
    KO_Grabbed_C,
    KO_Thrown_C,
    KO_AerialLightHit_C,
    KO_PlayerGrabbed_C,
    KO_PlayerThrown_C,
    KO_AerialHeavyHit_C,
    KO_KnockoutAssist_C,
    KO_Winner_C,
    NUMCAREERSTATS
};

static const std::map<std::string, int> eventDictionaryCareer = {
    { "FirstTouch", FirstTouch },
    { "Shot", Shot },
    { "Goal", Goal },
    { "Center", Center },
    { "HatTrick", HatTrick },
    { "Clear", Clear },
    { "Win", Win },
    { "MVP", MVP },
    { "Assist", Assist },
    { "Demolish", Demolish },
    { "Save", Save },
    { "Loss", Loss },
    { "AerialHit", AerialHit },
    { "EpicSave", EpicSave },
    { "LongGoal", LongGoal },
    { "PoolShot", PoolShot },
    { "BicycleHit", BicycleHit },
    { "BackwardsGoal", BackwardsGoal },
    { "JuggleHit", JuggleHit },
    { "Playmaker", Playmaker },
    { "OvertimeGoal", OvertimeGoal },
    { "Savior", Savior },
    { "FewestBallTouches", FewestBallTouches },
    { "CarTouches", CarTouches },
    { "FastestGoal", FastestGoal },
    { "SlowestGoal", SlowestGoal },
    { "FurthestGoal", FurthestGoal },
    { "MostBallTouches", MostBallTouches },
    { "MostBoostPickups", MostBoostPickups },
    { "Demolition", Demolition },
    { "BicycleGoal", BicycleGoal },
    { "AerialGoal", AerialGoal },
    { "FreezeSave", FreezeSave },
    { "OwnGoal", OwnGoal },
    { "TurtleGoal", TurtleGoal },
    { "FewestBoostPickups", FewestBoostPickups },
    { "BreakoutDamage", BreakoutDamage },
    { "BreakoutDamageLarge", BreakoutDamageLarge },
    { "TimePlayed", TimePlayed },
    { "LowFive", LowFive },
    { "HoopsSwishGoal", HoopsSwishGoal },
    { "BallHit", BallHit },
    { "HighFive", HighFive },
    { "BoostPickups", BoostPickups },
    { "KO_LightHit", KO_LightHit_C },
    { "KO_HeavyHit", KO_HeavyHit_C },
    { "KO_Knockout", KO_Knockout_C },
    { "KO_DoubleKO", KO_DoubleKO_C },
    { "KO_HitTaken", KO_HitTaken_C },
    { "KO_Death", KO_Death_C },
    { "KO_LightBlock", KO_LightBlock_C },
    { "KO_HeavyBlock", KO_HeavyBlock_C },
    { "KO_BlockTaken", KO_BlockTaken_C },
    { "KO_Grabbed", KO_Grabbed_C },
    { "KO_Thrown", KO_Thrown_C },
    { "KO_AerialLightHit", KO_AerialLightHit_C },
    { "KO_PlayerGrabbed", KO_PlayerGrabbed_C },
    { "KO_PlayerThrown", KO_PlayerThrown_C },
    { "KO_AerialHeavyHit", KO_AerialHeavyHit_C },
    { "KO_KnockoutAssist", KO_KnockoutAssist_C },
    { "KO_Winner", KO_Winner_C }
};

static std::string statStringsCareer[NUMCAREERSTATS] = {
    "CareerFirstTouches",
    "CareerShots",
    "CareerGoals",
    "CareerCenters",
    "CareerHatTricks",
    "CareerClears",
    "CareerWins",
    "CareerMVPs",
    "CareerAssists",
    "CareerDemolitions",
    "CareerSaves",
    "CareerLosses",
    "CareerAerialHits",
    "CareerEpicSaves",
    "CareerLongGoals",
    "CareerPoolShots",
    "CareerBicycleHits",
    "CareerBackwardsGoals",
    "CareerJuggleHits",
    "CareerPlaymakers",
    "CareerOvertimeGoals",
    "CareerSaviors",
    "CareerFewestBallTouches",
    "CareerCarTouches",
    "CareerFastestGoals",
    "CareerSlowestGoals",
    "CareerFurthestGoals",
    "CareerMostBallTouches",
    "CareerMostBoostPickups",
    "CareerExterminations",
    "CareerBicycleGoals",
    "CareerAerialGoals",
    "CareerFreezeSaves",
    "CareerOwnGoals",
    "CareerTurtleGoals",
    "CareerFewestBoostPickups",
    "CareerBreakoutDamages",
    "CareerBreakoutDamagesLarge",
    "CareerTimePlayed",
    "CareerLowFives",
    "CareerHoopsSwishGoals",
    "CareerBallHits",
    "CareerHighFives",
    "CareerBoostPickups",
    "CareerGames",
    "Career_KO_LightHit",
    "Career_KO_HeavyHit",
    "Career_KO_Knockout",
    "Career_KO_DoubleKO",
    "Career_KO_HitTaken",
    "Career_KO_Death",
    "Career_KO_LightBlock",
    "Career_KO_HeavyBlock",
    "Career_KO_BlockTaken",
    "Career_KO_Grabbed",
    "Career_KO_Thrown",
    "Career_KO_AerialLightHit",
    "Career_KO_PlayerGrabbed",
    "Career_KO_PlayerThrown",
    "Career_KO_AerialHeavyHit",
    "Career_KO_KnockoutAssist",
    "Career_KO_Winner",
};

static const char * statCharsCareer[NUMCAREERSTATS] = {
    "First Touches",
    "Shots",
    "Goals",
    "Centers",
    "Hat Tricks",
    "Clears",
    "Wins",
    "MVPs",
    "Assists",
    "Demolitions",
    "Saves",
    "Losses",
    "Aerial Hits",
    "Epic Saves",
    "Long Goals",
    "Pool Shots",
    "Bicycle Hits",
    "Backwards Goals",
    "Juggle Hits",
    "Playmakers",
    "Overtime Goals",
    "Saviors",
    "Fewest Ball Touches",
    "Car Touches",
    "Fastest Goals",
    "Slowest Goals",
    "Furthest Goals",
    "Most Ball Touches",
    "Most Boost Pickups",
    "Exterminations",
    "Bicycle Goals",
    "Aerial Goals",
    "Freeze Saves",
    "Own Goals",
    "Turtle Goals",
    "Fewest Boost Pickups",
    "Breakout Damages",
    "Breakout Damages Large",
    "Time Played",
    "Low Fives",
    "Hoops Swish Goals",
    "Ball Hits",
    "High Fives",
    "Boost Pickups",
    "Games",
    "KO Light Hits",
    "KO Heavy Hits",
    "KO Knockouts",
    "KO Double KOs",
    "KO Hits Taken",
    "KO Deaths",
    "KO Light Blocks",
    "KO Heavy Blocks",
    "KO Blocks Taken",
    "KO Times Grabbed",
    "KO Times Thrown",
    "KO Aerial Light Hits",
    "KO Players Grabbed",
    "KO Players Thrown",
    "KO Aerial Heavy Hits",
    "KO Knockout Assists",
    "KO Wins",
};

extern std::string renderStringsCareerTotal[NUMCAREERSTATS];
extern std::string renderStringsCareerPrivate[NUMCAREERSTATS];
extern std::string renderStringsCareerCasual[NUMCAREERSTATS];
extern std::string renderStringsCareerRanked[NUMCAREERSTATS];
extern std::string renderStringsCareerAverage[NUMCAREERSTATS];

extern std::string renderStringsTeam[ENDNORMALSTATS];
extern std::string renderStringsOpponent[ENDNORMALSTATS];

enum statStates {
    STAT_DEFAULT,
    STAT_AVERAGE,
    STAT_GAME,
    STAT_OTHER,
    STAT_CAREER_START = STAT_OTHER,
    STAT_CAREER_TOTAL,
    STAT_CAREER_PRIVATE,
    STAT_CAREER_RANKED,
    STAT_CAREER_CASUAL,
    STAT_CAREER_AVERAGE,
    STAT_TEAM_START = STAT_CAREER_AVERAGE,
    STAT_TEAM,
    STAT_TEAM_OPPONENT,
    STAT_END
};

extern std::string labelStringsStandard[NUMSTATS];
extern std::string labelStringsGame[NUMSTATS];
extern std::string labelStringsAverage[NUMSTATS];

extern std::string labelStringsOther[NUMOTHERSTATS];

extern std::string labelStringsCareerTotal[NUMCAREERSTATS];
extern std::string labelStringsCareerPrivate[NUMCAREERSTATS];
extern std::string labelStringsCareerCasual[NUMCAREERSTATS];
extern std::string labelStringsCareerRanked[NUMCAREERSTATS];
extern std::string labelStringsCareerAverage[NUMCAREERSTATS];

extern std::string labelStringsTeam[ENDNORMALSTATS];
extern std::string labelStringsOpponent[ENDNORMALSTATS];

// used for cvar names
extern std::string statStringsCareerTotal[NUMCAREERSTATS];
extern std::string statStringsCareerPrivate[NUMCAREERSTATS];
extern std::string statStringsCareerCasual[NUMCAREERSTATS];
extern std::string statStringsCareerRanked[NUMCAREERSTATS];
extern std::string statStringsCareerAverage[NUMCAREERSTATS];
extern std::string statStringsTeam[ENDNORMALSTATS];
extern std::string statStringsOpponent[ENDNORMALSTATS];

extern std::vector<std::string*> labelStrings;
extern std::vector<std::string*> renderStrings;
extern std::vector<std::string*> cvarBases;