#include "pch.h"
#include "Maps.h"

std::string indexStringMapRender[numStats] = {
    "Wins: ",
    "Losses: ",
    "MVPs: ",
    "Games: ",
    "Goals: ",
    "Demolitions: ",
    "Deaths: ",
    "Exterminations: ",
    "Aerial Goals: ",
    "Backwards Goals: ",
    "Bicycle Goals: ",
    "Long Goals: ",
    "Turtle Goals: ",
    "Pool Shots: ",
    "Overtime Goals: ",
    "Hat Tricks: ",
    "Assists: ",
    "Playmakers: ",
    "Saves: ",
    "Epic Saves: ",
    "Saviors: ",
    "Shots: ",
    "Centers: ",
    "Clears: ",
    "First Touches: ",
    "Damages: ",
    "Ultra Damages: ",
    "LowFives: ",
    "HighFives: ",
    "Swishs: ",
    "Bicycle Hits: ",
    "Points: ",
    "Total Saves: ",
    "Own Goals: ",
    "Time Played: ",
    "Offense Time: ",
    "Defense Time: "
};

std::string indexStringMapRenderGame[numStats] = {
    "Game Wins: ",
    "Game Losses: ",
    "Game MVPs: ",
    "Game Games: ",
    "Game Goals: ",
    "Game Demolitions: ",
    "Game Deaths: ",
    "Game Exterminations: ",
    "Game Aerial Goals: ",
    "Game Backwards Goals: ",
    "Game Bicycle Goals: ",
    "Game Long Goals: ",
    "Game Turtle Goals: ",
    "Game Pool Shots: ",
    "Game Overtime Goals: ",
    "Game Hat Tricks: ",
    "Game Assists: ",
    "Game Playmakers: ",
    "Game Saves: ",
    "Game Epic Saves: ",
    "Game Saviors: ",
    "Game Shots: ",
    "Game Centers: ",
    "Game Clears: ",
    "Game First Touches: ",
    "Game Damages: ",
    "Game Ultra Damages: ",
    "Game Low Fives: ",
    "Game High Fives: ",
    "Game Swishs: ",
    "Game Bicycle Hits: ",
    "Game Points: ",
    "Game Total Saves: ",
    "Game Own Goals: ",
    "Game Time Played: ",
    "Game Offense Time: ",
    "Game Defense Time: "
};

std::string averageStringsRender[numStats] = {
    "Average Wins: ",
    "Average Losses: ",
    "Average MVPs: ",
    "Average Games: ",
    "Average Goals: ",
    "Average Demolitions: ",
    "Average Deaths: ",
    "Average Exterminations: ",
    "Average Aerial Goals: ",
    "Average Backwards Goals: ",
    "Average Bicycle Goals: ",
    "Average Long Goals: ",
    "Average Turtle Goals: ",
    "Average PoolShots: ",
    "Average Overtime Goals: ",
    "Average Hat Tricks: ",
    "Average Assists: ",
    "Average Playmakers: ",
    "Average Saves: ",
    "Average Epic Saves: ",
    "Average Saviors: ",
    "Average Shots: ",
    "Average Centers: ",
    "Average Clears: ",
    "Average First Touchs: ",
    "Average Damages: ",
    "Average Ultra Damages: ",
    "Average Low Fives: ",
    "Average High Fives: ",
    "Average Swishs: ",
    "Average Bicycle Hits: ",
    "Average Points: ",
    "Average Total Saves: ",
    "Average Own Goals: ",
    "Average Time Played: ",
    "Average Offense Time: ",
    "Average Defense Time: "
};

std::string indexStringMapRenderOther[numOtherStats] = {
    "Shooting Percentage: ",
    "Game Shooting Percentage: ",
    "KD Ratio: ",
    "Game KD Ratio: ",
    "Possible Exterminations: ",
    "Missed Extermination Percent: ",
    "Win Percentage: "
};

std::string indexStringMapRenderCareerTotal[NUMCAREERSTATS] = {
    "Career Total First Touches: ",
    "Career Total Shots: ",
    "Career Total Goals: ",
    "Career Total Centers: ",
    "Career Total Hat Tricks: ",
    "Career Total Clears: ",
    "Career Total Wins: ",
    "Career Total MVPs: ",
    "Career Total Assists: ",
    "Career Total Demolitions: ",
    "Career Total Saves: ",
    "Career Total Losses: ",
    "Career Total Aerial Hits: ",
    "Career Total Epic Saves: ",
    "Career Total Long Goals: ",
    "Career Total Pool Shots: ",
    "Career Total Bicycle Hits: ",
    "Career Total Backwards Goals: ",
    "Career Total Juggle Hits: ",
    "Career Total Playmakers: ",
    "Career Total Overtime Goals: ",
    "Career Total Saviors: ",
    "Career Total Fewest Ball Touches: ",
    "Career Total Car Touches: ",
    "Career Total Fastest Goals: ",
    "Career Total Slowest Goals: ",
    "Career Total Furthest Goals: ",
    "Career Total Most Ball Touches: ",
    "Career Total Most Boost Pickups: ",
    "Career Total Exterminations: ",
    "Career Total Bicycle Goals: ",
    "Career Total Aerial Goals: ",
    "Career Total Freeze Saves: ",
    "Career Total Own Goals: ",
    "Career Total Turtle Goals: ",
    "Career Total Fewest Boost Pickups: ",
    "Career Total Breakout Damage: ",
    "Career Total Breakout Damage Large: ",
    "Career Total Time Played: ",
    "Career Total Low Fives: ",
    "Career Total Hoops Swish Goals: ",
    "Career Total Ball Hits: ",
    "Career Total High Fives: ",
    "Career Total Boost Pickups: "
};

std::string indexStringMapRenderCareerPrivate[NUMCAREERSTATS] = {
    "Career Private First Touches: ",
    "Career Private Shots: ",
    "Career Private Goals: ",
    "Career Private Centers: ",
    "Career Private Hat Tricks: ",
    "Career Private Clears: ",
    "Career Private Wins: ",
    "Career Private MVPs: ",
    "Career Private Assists: ",
    "Career Private Demolitions: ",
    "Career Private Saves: ",
    "Career Private Losses: ",
    "Career Private Aerial Hits: ",
    "Career Private Epic Saves: ",
    "Career Private Long Goals: ",
    "Career Private Pool Shots: ",
    "Career Private Bicycle Hits: ",
    "Career Private Backwards Goals: ",
    "Career Private Juggle Hits: ",
    "Career Private Playmakers: ",
    "Career Private Overtime Goals: ",
    "Career Private Saviors: ",
    "Career Private Fewest Ball Touches: ",
    "Career Private Car Touches: ",
    "Career Private Fastest Goals: ",
    "Career Private Slowest Goals: ",
    "Career Private Furthest Goals: ",
    "Career Private Most Ball Touches: ",
    "Career Private Most Boost Pickups: ",
    "Career Private Exterminations: ",
    "Career Private Bicycle Goals: ",
    "Career Private Aerial Goals: ",
    "Career Private Freeze Saves: ",
    "Career Private Own Goals: ",
    "Career Private Turtle Goals: ",
    "Career Private Fewest Boost Pickups: ",
    "Career Private Breakout Damage: ",
    "Career Private Breakout Damage Large: ",
    "Career Private Time Played: ",
    "Career Private Low Fives: ",
    "Career Private Hoops Swish Goals: ",
    "Career Private Ball Hits: ",
    "Career Private High Fives: ",
    "Career Private Boost Pickups: "
};

std::string indexStringMapRenderCareerCasual[NUMCAREERSTATS] = {
    "Career Casual First Touches: ",
    "Career Casual Shots: ",
    "Career Casual Goals: ",
    "Career Casual Centers: ",
    "Career Casual Hat Tricks: ",
    "Career Casual Clears: ",
    "Career Casual Wins: ",
    "Career Casual MVPs: ",
    "Career Casual Assists: ",
    "Career Casual Demolitions: ",
    "Career Casual Saves: ",
    "Career Casual Losses: ",
    "Career Casual Aerial Hits: ",
    "Career Casual Epic Saves: ",
    "Career Casual Long Goals: ",
    "Career Casual Pool Shots: ",
    "Career Casual Bicycle Hits: ",
    "Career Casual Backwards Goals: ",
    "Career Casual Juggle Hits: ",
    "Career Casual Playmakers: ",
    "Career Casual Overtime Goals: ",
    "Career Casual Saviors: ",
    "Career Casual Fewest Ball Touches: ",
    "Career Casual Car Touches: ",
    "Career Casual Fastest Goals: ",
    "Career Casual Slowest Goals: ",
    "Career Casual Furthest Goals: ",
    "Career Casual Most Ball Touches: ",
    "Career Casual Most Boost Pickups: ",
    "Career Casual Exterminations: ",
    "Career Casual Bicycle Goals: ",
    "Career Casual Aerial Goals: ",
    "Career Casual Freeze Saves: ",
    "Career Casual Own Goals: ",
    "Career Casual Turtle Goals: ",
    "Career Casual Fewest Boost Pickups: ",
    "Career Casual Breakout Damage: ",
    "Career Casual Breakout Damage Large: ",
    "Career Casual Time Played: ",
    "Career Casual Low Fives: ",
    "Career Casual Hoops Swish Goals: ",
    "Career Casual Ball Hits: ",
    "Career Casual High Fives: ",
    "Career Casual Boost Pickups: "
};

std::string indexStringMapRenderCareerRanked[NUMCAREERSTATS] = {
    "Career Ranked First Touches: ",
    "Career Ranked Shots: ",
    "Career Ranked Goals: ",
    "Career Ranked Centers: ",
    "Career Ranked Hat Tricks: ",
    "Career Ranked Clears: ",
    "Career Ranked Wins: ",
    "Career Ranked MVPs: ",
    "Career Ranked Assists: ",
    "Career Ranked Demolitions: ",
    "Career Ranked Saves: ",
    "Career Ranked Losses: ",
    "Career Ranked Aerial Hits: ",
    "Career Ranked Epic Saves: ",
    "Career Ranked Long Goals: ",
    "Career Ranked Pool Shots: ",
    "Career Ranked Bicycle Hits: ",
    "Career Ranked Backwards Goals: ",
    "Career Ranked Juggle Hits: ",
    "Career Ranked Playmakers: ",
    "Career Ranked Overtime Goals: ",
    "Career Ranked Saviors: ",
    "Career Ranked Fewest Ball Touches: ",
    "Career Ranked Car Touches: ",
    "Career Ranked Fastest Goals: ",
    "Career Ranked Slowest Goals: ",
    "Career Ranked Furthest Goals: ",
    "Career Ranked Most Ball Touches: ",
    "Career Ranked Most Boost Pickups: ",
    "Career Ranked Exterminations: ",
    "Career Ranked Bicycle Goals: ",
    "Career Ranked Aerial Goals: ",
    "Career Ranked Freeze Saves: ",
    "Career Ranked Own Goals: ",
    "Career Ranked Turtle Goals: ",
    "Career Ranked Fewest Boost Pickups: ",
    "Career Ranked Breakout Damage: ",
    "Career Ranked Breakout Damage Large: ",
    "Career Ranked Time Played: ",
    "Career Ranked Low Fives: ",
    "Career Ranked Hoops Swish Goals: ",
    "Career Ranked Ball Hits: ",
    "Career Ranked High Fives: ",
    "Career Ranked Boost Pickups: "
};

std::string indexStringMapRenderCareerAverage[NUMCAREERSTATS] = {
    "Career Average First Touches: ",
    "Career Average Shots: ",
    "Career Average Goals: ",
    "Career Average Centers: ",
    "Career Average Hat Tricks: ",
    "Career Average Clears: ",
    "Career Average Wins: ",
    "Career Average MVPs: ",
    "Career Average Assists: ",
    "Career Average Demolitions: ",
    "Career Average Saves: ",
    "Career Average Losses: ",
    "Career Average Aerial Hits: ",
    "Career Average Epic Saves: ",
    "Career Average Long Goals: ",
    "Career Average Pool Shots: ",
    "Career Average Bicycle Hits: ",
    "Career Average Backwards Goals: ",
    "Career Average Juggle Hits: ",
    "Career Average Playmakers: ",
    "Career Average Overtime Goals: ",
    "Career Average Saviors: ",
    "Career Average Fewest Ball Touches: ",
    "Career Average Car Touches: ",
    "Career Average Fastest Goals: ",
    "Career Average Slowest Goals: ",
    "Career Average Furthest Goals: ",
    "Career Average Most Ball Touches: ",
    "Career Average Most Boost Pickups: ",
    "Career Average Exterminations: ",
    "Career Average Bicycle Goals: ",
    "Career Average Aerial Goals: ",
    "Career Average Freeze Saves: ",
    "Career Average Own Goals: ",
    "Career Average Turtle Goals: ",
    "Career Average Fewest Boost Pickups: ",
    "Career Average Breakout Damage: ",
    "Career Average Breakout Damage Large: ",
    "Career Average Time Played: ",
    "Career Average Low Fives: ",
    "Career Average Hoops Swish Goals: ",
    "Career Average Ball Hits: ",
    "Career Average High Fives: ",
    "Career Average Boost Pickups: "
};