#include "pch.h"
#include "Maps.h"

std::string indexStringMapRender[numStats] = {
    "Wins: ",
    "Losses: ",
    "MVPs: ",
    "Games: ",
    "Goals: ",
    "Demolitions: ",
    "Deaths: ",
    "Exterminations: ",
    "Aerial Goals: ",
    "Backwards Goals: ",
    "Bicycle Goals: ",
    "Long Goals: ",
    "Turtle Goals: ",
    "Pool Shots: ",
    "Overtime Goals: ",
    "Hat Tricks: ",
    "Assists: ",
    "Playmakers: ",
    "Saves: ",
    "Epic Saves: ",
    "Saviors: ",
    "Shots: ",
    "Centers: ",
    "Clears: ",
    "First Touches: ",
    "Damages: ",
    "Ultra Damages: ",
    "LowFives: ",
    "HighFives: ",
    "Swishs: ",
    "Bicycle Hits: ",
    "Points: ",
    "Total Saves: ",
    "Own Goals: ",
    "Time Played: ",
    "Offense Time: ",
    "Defense Time: "
};

std::string indexStringMapRenderGame[numStats] = {
    "Game Wins: ",
    "Game Losses: ",
    "Game MVPs: ",
    "Game Games: ",
    "Game Goals: ",
    "Game Demolitions: ",
    "Game Deaths: ",
    "Game Exterminations: ",
    "Game Aerial Goals: ",
    "Game Backwards Goals: ",
    "Game Bicycle Goals: ",
    "Game Long Goals: ",
    "Game Turtle Goals: ",
    "Game Pool Shots: ",
    "Game Overtime Goals: ",
    "Game Hat Tricks: ",
    "Game Assists: ",
    "Game Playmakers: ",
    "Game Saves: ",
    "Game Epic Saves: ",
    "Game Saviors: ",
    "Game Shots: ",
    "Game Centers: ",
    "Game Clears: ",
    "Game First Touches: ",
    "Game Damages: ",
    "Game Ultra Damages: ",
    "Game Low Fives: ",
    "Game High Fives: ",
    "Game Swishs: ",
    "Game Bicycle Hits: ",
    "Game Points: ",
    "Game Total Saves: ",
    "Game Own Goals: ",
    "Game Time Played: ",
    "Game Offense Time: ",
    "Game Defense Time: "
};

std::string averageStringsRender[numStats] = {
    "Average Wins: ",
    "Average Losses: ",
    "Average MVPs: ",
    "Average Games: ",
    "Average Goals: ",
    "Average Demolitions: ",
    "Average Deaths: ",
    "Average Exterminations: ",
    "Average Aerial Goals: ",
    "Average Backwards Goals: ",
    "Average Bicycle Goals: ",
    "Average Long Goals: ",
    "Average Turtle Goals: ",
    "Average PoolShots: ",
    "Average Overtime Goals: ",
    "Average Hat Tricks: ",
    "Average Assists: ",
    "Average Playmakers: ",
    "Average Saves: ",
    "Average Epic Saves: ",
    "Average Saviors: ",
    "Average Shots: ",
    "Average Centers: ",
    "Average Clears: ",
    "Average First Touchs: ",
    "Average Damages: ",
    "Average Ultra Damages: ",
    "Average Low Fives: ",
    "Average High Fives: ",
    "Average Swishs: ",
    "Average Bicycle Hits: ",
    "Average Points: ",
    "Average Total Saves: ",
    "Average Own Goals: ",
    "Average Time Played: ",
    "Average Offense Time: ",
    "Average Defense Time: "
};

std::string indexStringMapRenderOther[numOtherStats] = {
    "Shooting Percentage: ",
    "Game Shooting Percentage: ",
    "KD Ratio: ",
    "Game KD Ratio: ",
    "Possible Exterminations: ",
    "Missed Extermination Percent: ",
    "Win Percentage: "
};

std::string indexStringMapRenderCareerTotal[NUMCAREERSTATS] = {
    "Career Total First Touches: ",
    "Career Total Shots: ",
    "Career Total Goals: ",
    "Career Total Centers: ",
    "Career Total Hat Tricks: ",
    "Career Total Clears: ",
    "Career Total Wins: ",
    "Career Total MVPs: ",
    "Career Total Assists: ",
    "Career Total Demolitions: ",
    "Career Total Saves: ",
    "Career Total Losses: ",
    "Career Total Aerial Hits: ",
    "Career Total Epic Saves: ",
    "Career Total Long Goals: ",
    "Career Total Pool Shots: ",
    "Career Total Bicycle Hits: ",
    "Career Total Backwards Goals: ",
    "Career Total Juggle Hits: ",
    "Career Total Playmakers: ",
    "Career Total Overtime Goals: ",
    "Career Total Saviors: ",
    "Career Total Fewest Ball Touches: ",
    "Career Total Car Touches: ",
    "Career Total Fastest Goals: ",
    "Career Total Slowest Goals: ",
    "Career Total Furthest Goals: ",
    "Career Total Most Ball Touches: ",
    "Career Total Most Boost Pickups: ",
    "Career Total Exterminations: ",
    "Career Total Bicycle Goals: ",
    "Career Total Aerial Goals: ",
    "Career Total Freeze Saves: ",
    "Career Total Own Goals: ",
    "Career Total Turtle Goals: ",
    "Career Total Fewest Boost Pickups: ",
    "Career Total Breakout Damage: ",
    "Career Total Breakout Damage Large: ",
    "Career Total Time Played: ",
    "Career Total Low Fives: ",
    "Career Total Hoops Swish Goals: ",
    "Career Total Ball Hits: ",
    "Career Total High Fives: ",
    "Career Total Boost Pickups: "
};